# アクション名
name: CI

# タイミングを指定
on:
  pull_request:
    branches: [main]

jobs:
  run-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: install dependencies
        run: npm i

      - name: run jest
        run: npm run test

      - name: upload test coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

      - name: show coverage in comments
        uses: ziishaned/jest-reporter-action@0.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: "npm run jest --coverage"
